services:
  gemini-reader:
    build: .
    container_name: gemini-reader
    hostname: gemini-reader
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./data:/app/data
    command: ["uv", "run", "python", "main.py", "--file", "/app/data/anna-kendrick.json"]
    networks:
      - main-network

networks:
  main-network:
    external: true
